### ISSUE TITLE
Problem with runing DVB inspector under Windows 10 x64

### ISSUE THREAD

**Issue by netdvb** [EricBerendsen/dvbinspector#50]
Hello
After download form git version DVBinspector-1.16.1-dist i when i try start from dvb.bat get error as below 

set JVM_FLAGS=

java -classpath .;.\lib\jfreechart-1.5.3.jar;.\lib\opencsv-5.5.2.jar;.\lib\jlayer-1.0.1.4.jar;.\lib\commons-text-1.9.jar;.\lib\commons-logging-1.2.jar;.\lib\commons-lang3-3.12.0.jar;.\lib\commons-collections4-4.4.jar;.\lib\commons-collections-3.2.2.jar;.\lib\commons-beanutils-1.9.4.jar;.\DVBinspector.jar  -Djava.util.logging.config.file=src/main/resources/logging.properties nl.digitalekabeltelevisie.main.DVBinspector
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: nl/digitalekabeltelevisie/main/DVBinspector has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)

I have installed Java x64 in system version 8 update 351.

**Comment by EricBerendsen** [comment]
You got an old version of java. For some reason Oracle keeps om providing java 8 from [https://www.java.com/en/](https://www.java.com/en/), the most logical place where people start looking for java. 

However DVB Inspector 1.16.1 requires java 11, but DVB Inspector 17 (out in a few weeks) will need java 17.  You can find the Oracle implementation at [https://www.oracle.com/java/technologies/downloads/#java17](https://www.oracle.com/java/technologies/downloads/#java17)

**Comment by netdvb** [comment]
Problem resolved, thank you for your support.
