### ISSUE TITLE
Crash in JPEG XS descriptor handler

### ISSUE THREAD

**Issue by efykse** [EricBerendsen/dvbinspector#54]
DVB Inspector 1.17.0 is crashing when analyzing the PMT in this TS recording:
[xs_descriptor.zip](https://github.com/EricBerendsen/dvbinspector/files/10040981/xs_descriptor.zip)

It seems maybe it is expecting some private byte at the end of the descriptor, but as far as I know this is optional.

```
SEVERE: Error displaying stream
java.lang.NullPointerException: Cannot read the array length because "value" is null
        at nl.digitalekabeltelevisie.controller.KVP.<init>(KVP.java:223)
        at nl.digitalekabeltelevisie.data.mpeg.descriptors.extension.mpeg.JpegXsVideoDescriptor.getJTreeNode(JpegXsVideoDescriptor.java:105)
        at nl.digitalekabeltelevisie.util.Utils.addToList(Utils.java:1223)
        at nl.digitalekabeltelevisie.util.Utils.addListJTree(Utils.java:1202)
...
```

**Comment by EricBerendsen** [comment]
Thanks for reporting this. You are completely right, the private bytes are optional. Fixed now, if you need a snapshot version with the fix included you can find it [at the actions tab](https://github.com/EricBerendsen/dvbinspector/actions/runs/3499689390)
