### ISSUE TITLE
Version 1.19 released

### ISSUE THREAD

**Issue by EricBerendsen** [EricBerendsen/dvbinspector#74]
Just released version 1.19

Most obvious change in this release is the LookAndFeel. Until now DVB Inspector used the "SystemLookAndFeel", where java tries to look as much as possible like a native application. I noticed for Windows with a 4K hiDPI screen this resulted in long start up times (>20 seconds) The performance is much better with the java default LookAndFeel.

A larger change is the support for AVCHD/Blu-ray M2TS files. DVB Inspector is and always will be a **DVB** analyzer first. But a lot of people (ab)used it by parsing m2ts streams, like used in Blu-ray and/or video-camera's. AVCHD uses 192 byte packets, but the 4 extra bytes are at the start of the packet (and contain a TP_header with arrival time information). DVB Inspector presented those packets with 4 extra bytes at the and, but those 4 bytes belonged to the next packet.

This is now fixed, streams with 192 bytes packet size will always be handled as AVCHD streams with the TP_header at the start of the packet. The timing info in the packets is now also used for calculations, so the various charts now correctly handle VBR AVCHD streams.

For all other packet size DVB Inspector still expects constant bitrate full MPEG transport streams.

Feedback/ bug reports are, as always, welcome.

**Comment by ValeZAA** [comment]
dvb.bat does not work here unless I put lib\opencsv-5.5.2.jar from 1.18.0. New version that is packaged does not work.

**Comment by EricBerendsen** [comment]
Thank you for reporting this, fixed in 1.19.1.

**Comment by EnoSat** [comment]
d:\DVBinspector>java -classpath .;.\lib\jfreechart-1.5.3.jar;.\lib\opencsv-5.7.1.jar;.\lib\jlayer-1.0.1.4.jar;.\lib\commons-text-1.9.jar;.\lib\commons-logging-1.2.jar;.\lib\commons-lang3-3.12.0.jar;.\lib\commons-collections4-4.4.jar;.\lib\commons-collections-3.2.2.jar;.\lib\commons-beanutils-1.9.4.jar;.\DVBinspector.jar  -Djava.util.logging.config.file=src/main/resources/logging.properties nl.digitalekabeltelevisie.main.DVBinspector
Exception in thread "main" java.lang.UnsupportedClassVersionError: nl/digitalekabeltelevisie/main/DVBinspector has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)

d:\DVBinspector>

**Comment by EricBerendsen** [comment]
@EnoSat  For DVB Inspector you need to have at least java version 17. From the stack trace I think you are still on java 8 (or 1.8)
To see which version of java is used try "java -version"

The next version of DVB Inspector will need java 21, so its better to upgrade to java 21.

**Comment by EnoSat** [comment]
Hi,
java -version
java version "1.8.0_421"
Java(TM) SE Runtime Environment (build 1.8.0_421-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.421-b09, mixed mode)

Can JDK 23 also be used?
https://www.oracle.com/java/technologies/downloads/
